<?php
define('QR_DIR',BASE_PATH.DIRECTORY_SEPARATOR.'qrimg'.DIRECTORY_SEPARATOR);
define('QR_LIB',BASE_PATH.DIRECTORY_SEPARATOR.'protected'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'phpqrcode'.DIRECTORY_SEPARATOR.'qrlib.php');
define('PHP_MAILER_LIB',BASE_PATH.DIRECTORY_SEPARATOR.'protected'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'phpmailer'.DIRECTORY_SEPARATOR.'PHPMailerAutoload.php');
define('PDF_LIB',BASE_PATH.DIRECTORY_SEPARATOR.'protected'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'tcpdf'.DIRECTORY_SEPARATOR.'tcpdf.php');
define('PDF_LIB_FONTS',BASE_PATH.DIRECTORY_SEPARATOR.'protected'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR.'tcpdf'.DIRECTORY_SEPARATOR.'fonts');